### ISSUE TITLE
Polaris import error

### ISSUE THREAD

**Issue by Ljohn89** [polaris-hub/polaris-method-comparison#3]
Hi, 
Can I know what version of sqlalchemy is to be installed ?
The version that i have is 2.0.36, but while importing polaris, it is throwing error, 

{
	"name": "AttributeError",
	"message": "module 'sqlalchemy' has no attribute '__all__'",
	"stack": "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 7
      5 from rdkit.Chem import Descriptors
      6 from tqdm.auto import tqdm
----> 7 import polaris as po
      9 tqdm.pandas()

}
--
LJ

**Comment by PatWalters** [comment]
Polaris bug reports should be posted in the polaris-hub repo. 
https://github.com/polaris-hub/polaris/issues
Can you repost there?  Sorry to pass the buck

**Comment by Ljohn89** [comment]
Sure, I will do it.

**Comment by cwognum** [comment]
Hey @Ljohn89 , I've answered you there, so I'll close this issue!
